server:
  port: 9090

spring:
  profiles:
    active: kafka
  application:
    name: smat-be
  data:
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    username: 'admin'
    password: 'admin'
    url: "jdbc:postgresql://localhost:5432/smat"

springdoc:
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.smat: DEBUG
    org.springframework.web: DEBUG
    com.fasterxml.jackson: DEBUG
